export interface Solicitud {
  id?: string;
  codigo?: string;
  solicitudId?: string;
  tramite?: string;
  tipoTramite?: string;
  tipoPatente?: string;
  estado?: string;
  area?: string;
  departamento?: string;
  areaResponsable?: string;
  datosTramite?: Record<string, string>;
  correoEnviado?: boolean;
  encargado?: string;
  funcionario?: string;
  asignadoA?: string;
  funcionarioAsignado?: string;
  funcionarioId?: string | number;
  cargoFuncionario?: string;
  numeroEmpleadoFuncionario?: string;
  fechaIngreso?: string;
  ultimaActualizacion?: string;
  solicitante?: string;
  nombreSolicitante?: string;
  razonSocial?: string;
  rut?: string;
  correo?: string;
  email?: string;
  telefono?: string;
  contacto?: string;
  direccion?: string;
  giro?: string;
  superficie?: string;
  observacion?: string;
  observaciones?: string;
  comentarioFuncionario?: string;
  documentosFaltantes?: string[] | string;
  fechaLimiteDocumentos?: string;
  [key: string]: unknown;
}
